// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFp_YgbKdQoOEdluz2KQAsMrJgr_O-okE',
    appId: '1:754996076373:web:944b6f55e324ea6b3e59dc',
    messagingSenderId: '754996076373',
    projectId: 'ohftok-gauntlet',
    authDomain: 'ohftok-gauntlet.firebaseapp.com',
    databaseURL: 'https://ohftok-gauntlet-default-rtdb.firebaseio.com',
    storageBucket: 'ohftok-gauntlet.firebasestorage.app',
    measurementId: 'G-5XV068JNFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1hd1aZopeDjtw8ROSsJlplXZfSAaEZU',
    appId: '1:754996076373:android:7dbd08fc5eabcf7b3e59dc',
    messagingSenderId: '754996076373',
    projectId: 'ohftok-gauntlet',
    databaseURL: 'https://ohftok-gauntlet-default-rtdb.firebaseio.com',
    storageBucket: 'ohftok-gauntlet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAql8TKIBbseJWBtCK2iukGb0iswhaj2BY',
    appId: '1:754996076373:ios:33c4c7bd8bf9e5153e59dc',
    messagingSenderId: '754996076373',
    projectId: 'ohftok-gauntlet',
    databaseURL: 'https://ohftok-gauntlet-default-rtdb.firebaseio.com',
    storageBucket: 'ohftok-gauntlet.firebasestorage.app',
    iosClientId: '754996076373-mlpp36kp871qb6bnnojnikutdmo3orav.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohftokv3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAql8TKIBbseJWBtCK2iukGb0iswhaj2BY',
    appId: '1:754996076373:ios:33c4c7bd8bf9e5153e59dc',
    messagingSenderId: '754996076373',
    projectId: 'ohftok-gauntlet',
    databaseURL: 'https://ohftok-gauntlet-default-rtdb.firebaseio.com',
    storageBucket: 'ohftok-gauntlet.firebasestorage.app',
    iosClientId: '754996076373-mlpp36kp871qb6bnnojnikutdmo3orav.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohftokv3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFp_YgbKdQoOEdluz2KQAsMrJgr_O-okE',
    appId: '1:754996076373:web:6b2aa54676ac23e23e59dc',
    messagingSenderId: '754996076373',
    projectId: 'ohftok-gauntlet',
    authDomain: 'ohftok-gauntlet.firebaseapp.com',
    databaseURL: 'https://ohftok-gauntlet-default-rtdb.firebaseio.com',
    storageBucket: 'ohftok-gauntlet.firebasestorage.app',
    measurementId: 'G-2D569895VN',
  );
}
